### PR TITLE
(1) Migrated to swift3 (2) Support for Couchbase Mobile 1.4 (3)iOS10 …

### PR DESCRIPTION
**Pull request by rajagp**
…SDK / XCode 8.3 compatibility (4) Updates to handle privacy requirements in iOS10 w.r.t. camera and photos access

### CODE REVIEW

**Comment by pasin** [comment]
@rajagp Have you run some tests? If so, I will just merge it.

**Comment by rajagp** [comment]
I ran the app on my iPhone ( simulator)  and tested send (and receive) of photos

**Comment by pasin** [comment]
I saw Pods folder get committed as well. I don't know why it doesn't get ignored. Can you clean that?

**Comment by rajagp** [comment]
Funny that .gitignore didn’t take care of it. I’ve removed Pods folder for the commit and also updated the README.

**Pull request merged**
